@startuml dm-c4-dynamic-abac
!include <C4/C4_Dynamic>
skinparam noteTextAlignment left
<style>
note {
  MaximumWidth 500
  FontName courier
  BackgroundColor white
}
</style>
left to right direction

Person(user, "User")
artifact "ID Token" as id {
  json claims {
    "name":"Luna Li",
    "email":"ll@depta.gov.uk",
    "roles": ["supplier", "acquirer"],
    "dept":"Dept A"
  }
}

System_Boundary(dm, "Data Marketplace") {
  Container_Boundary(acc, "Access control") {
    Component(policy,"Policy Evaluator")
  }

  artifact "Data Asset" as asset {
    json "metadata" as attr {
      "name": "Dataset X",
      "owner": "ll@depta.gov.uk",
      "classification": "OFFICIAL",
      "visibility": "PUBLIC",
      "dept": "Dept A",
      "columns": [{
            "titles": "colA",
            "classification": "OFFICIAL"
          },{
            "titles": "colB",
            "classification": "OFFICIAL-SENSITIVE"
          }]
    }
  }

  note as n2
    4. Deny access  <font:arial><color:red>X
  endnote

  policy - n2
}

note as n1
   <font:arial>3. Evaluate policy</font>

   <color:blue>Scenario:</color> Acquirers can NOT see OFFICIAL-SENSITIVE metadata
   <color:blue>Given</color> I am a data acquirer
   <color:blue>  And</color> I am signed into the data marketplace
   <color:blue>When</color> I view metadata about a data asset
    <color:blue>  And</color> that metadata is classified OFFICIAL-SENSITIVE
   <color:blue>Then</color> I am NOT able to view that metadata
endnote

claims - user
id --> policy : 1. Request 'read' access\l    to 'Dataset X'`\l    colB metadata\l
policy <-- attr : 2. Query data\l    asset metadata \l    attributes\l
n1 - policy

@enduml


