@startuml dm-c4-dynamic-abac
!include <C4/C4_Dynamic>
skinparam noteTextAlignment left
<style>
note {
  MaximumWidth 500
  FontName courier
  BackgroundColor white
}
</style>
left to right direction

Person(user, "User")
artifact "ID Token" as id {
  json claims {
    "name":"Luna Li",
    "email":"ll@depta.gov.uk",
    "roles": ["supplier", "acquirer"],
    "dept":"Dept A"
  }
}

System_Boundary(dm, "Data Marketplace") {
  Container_Boundary(acc, "Access control") {
    Component(policy,"Policy Evaluator")
  }

  artifact "Data Asset" as asset {
    json "attributes" as attr {
      "name": "Dataset X",
      "owner": "ll@depta.gov.uk",
      "classification": "OFFICIAL",
      "visibility": "PUBLIC",
      "dept": "Dept A"
    }
  }
}

note as n1
   <font:arial>3. Evaluate policy</font>

   <color:blue>Scenario:</color> Owners can edit data assets
   <color:blue>Given</color> I am a data supplier
   <color:blue>  And</color> I am the data asset owner
   <color:blue>When</color> I try to edit the data asset
   <color:blue>Then</color> I am allowed to edit the data asset
endnote

user - id
id --> policy : 1. Request 'edit' access\l    to 'Dataset X'
policy <-- attr : 2. Query data\l    asset attributes
policy - n1
policy --> asset : 4. Grant access

@enduml