@startuml dm-c4-component-discover 
!include <C4/C4_Component>

'LAYOUT_TOP_DOWN()
'LAYOUT_WITH_LEGEND()
left to right direction

'title C4 component diagram for Data Marketplace Discover service

AddElementTag("record", $bgColor="LightGrey", $borderColor="White")

Person(acquirer, "Acquirer", "")
Person(supplier, "Supplier", "")

System_Boundary(dm, "Data Marketplace") {
  Component(access, "Access control", "ABAC")  
  System_Boundary(discover, "Discover service") {
    Component(publish, "Publish metadata", "sub-service")
    Component(find, "Find metadata", "sub-service")
  }
  ComponentDb(CKAN,"Data catalogue","CKAN") {
    Component(asset,"Data asset record", $tags="record") {
    artifact "metadata" as metadata #orange
    artifact "OFFSEN\nmetadata" as metadatar
    }

    metadata - metadatar
  }
}
supplier --> access #green : <color:green>Publishes\l<color:green>metadata
access --> publish #green : <color:green>Grant
publish --> metadata #green
publish --> metadatar #green

acquirer --> access #orange : <color:orange>Search for data asset metadata\l
access --> find #orange : <color:orange>Grant
find --> metadata #orange : <color:orange>Can see

'layout
supplier -[#hidden] acquirer
@enduml