@startuml dm-c4-container 
!include <C4/C4_Container>
!include <C4/C4_Component>
left to right direction

  'title C4 Container diagram for Data Marketplace
  
  AddRelTag("dashed", $lineStyle=DashedLine())

  Person(acquirer, "Acquirer", "")
  Person(supplier, "Supplier", "")
  Person(admin, "Admin", "")

  Person_Ext(visitor, "Visitor", "")

  Container_Ext(idp, "Identity\nprovider", "")

  System_Boundary(dm, "Data Marketplace") {
  
    Container(am, "Access\ncontrol", "")
    Container(discover, "Discover", "")
    Container(share, "Share", "")
    Container(deliver, "Deliver", "") 
    Container(guide, "Guide", "") 
    SystemDb(catalog, "Data\nCatalogue", "")
    SystemQueue(workflow, "Workflow")
    SystemDb(cms, "Content")

    Boundary(common, "Shared services") {
      Container(logging, "Logging", "")
      Container(monitoring, "Monitoring", "")
      Container(reporting, "Reporting", "")  
      Container(backup, "Backup &\nRecovery", "")     
    }
    catalog -[#hidden]- logging 
    reporting -[#hidden] backup
  }

  Rel_U(supplier, idp, "", $tags="dashed")
  Rel_U(acquirer, idp, "", $tags="dashed")
  Rel_U(admin, idp, "", $tags="dashed")
  
  Rel(supplier, am, "")
  Rel(acquirer, am, "")
  Rel(admin, am, "")
  Rel(visitor, am, "")

  Rel(am, discover, "")
  Rel(am, share, "")
  Rel(am, deliver, "")
  Rel(am, guide, "")

  Rel(discover, catalog, "")
  Rel(share, catalog, "")
  Rel(deliver, catalog, "", $tags="dashed")
  
  Rel(share, workflow, "")
  Rel_R(catalog, workflow, "")

  Rel(guide, cms, "")
  'LAYOUT_WITH_LEGEND()
@enduml
