@startuml dm-c4-container 
!include <C4/C4_Container>
!include <C4/C4_Component>

  title C4 Container diagram for Data Marketplace
  
  AddRelTag("dashed", $lineStyle=DashedLine())

  Person(acquirer, "Acquirer", "")
  Person(supplier, "Supplier", "")
  Person(admin, "Admin", "")

  Person_Ext(learner, "Learner", "")

  Container_Ext(idp, "Identity provider", "")

  System_Boundary(dm, "Data Marketplace") {
  
    Container(am, "Access control", "")
    Container(discover, "Discover", "")
    Container(share, "Share", "")
    Container(access, "Access", "") 
    Container(learn, "Learn", "") 
    SystemDb(catalog, "Data Catalogue", "")

    Boundary(common, "Shared services") {
      Container(logging, "Logging", "")
      Container(monitoring, "Monitoring", "")
      Container(reporting, "Reporting", "")  
      Container(backup, "Backup & Recovery", "")     
    }
    catalog -[#hidden]- logging 
  }

  Rel_U(supplier, idp, "", $tags="dashed")
  Rel_U(acquirer, idp, "", $tags="dashed")
  Rel_U(admin, idp, "", $tags="dashed")
  
  Rel(supplier, am, "")
  Rel(acquirer, am, "")
  Rel(admin, am, "")
  Rel(learner, am, "")

  Rel(am, discover, "")
  Rel(am, share, "")
  Rel(am, access, "")
  Rel(am, learn, "")

  Rel(discover, catalog, "")
  Rel(share, catalog, "")
  Rel(access, catalog, "", $tags="dashed")

  LAYOUT_WITH_LEGEND()
@enduml
