@startuml dm-c4-component-auth 
!include <C4/C4_Component>

title C4 component diagram for Data Marketplace authentication
  
Person(user, "User", "")

System_Boundary(idp, "Identity Provider") {
  ComponentDb(ldap,"Directory","") 
  Component(auth, "Authorisation\nServer")
}

System_Boundary(dm, "Data Marketplace") {
  Component(discover, "Discover")
  Component(ac, "Access\ncontrol")
}

user -up-> auth : sign-in
auth . ldap : verify

user --> ac : present credentials
ac . discover : grant access

@enduml