@startuml dm-c4-container 
!include <C4/C4_Container>
!include <C4/C4_Component>
left to right direction

  'title C4 Container diagram for Data Marketplace
  
  AddRelTag("dashed", $lineStyle=DashedLine())

  Person(acquirer, "Acquirer", "", $tags="mvp")
  Person(supplier, "Supplier", "", $tags="mvp")
  Person(admin, "Admin", "", $tags="tobe")

  Person_Ext(visitor, "Visitor", "", $tags="tobe")

  Container_Ext(idp, "Identity\nprovider", "", $tags="mvp")

  System_Boundary(dm, "Data Marketplace") {
  
    Container(am, "Access\ncontrol", "", $tags="tobe")
    Container(discover, "Discover", "", $tags="mvp")
    Container(share, "Share", "", $tags="mvp")
    Container(deliver, "Deliver", "", $tags="tobe") 
    Container(guide, "Guide", "", $tags="tobe") 
    SystemDb(catalog, "Data\nCatalogue", "", $tags="mvp")
    SystemQueue(workflow, "Workflow", $tags="tobe")
    SystemDb(cms, "Content", $tags="tobe")

    Boundary(common, "Shared services") {
      Container(logging, "Logging", "", $tags="tobe")
      Container(monitoring, "Monitoring", "", $tags="tobe")
      Container(reporting, "Reporting", "", $tags="tobe")  
      Container(backup, "Backup &\nRecovery", "", $tags="tobe")     
    }
    catalog -[#hidden]- logging 
    reporting -[#hidden] backup
  }

  Rel_U(supplier, idp, "", $tags="dashed")
  Rel_U(acquirer, idp, "", $tags="dashed")
  Rel_U(admin, idp, "", $tags="dashed")
  
  Rel(supplier, am, "")
  Rel(acquirer, am, "")
  Rel(admin, am, "")
  Rel(visitor, am, "")

  Rel(am, discover, "")
  Rel(am, share, "")
  Rel(am, deliver, "")
  Rel(am, guide, "")

  Rel(discover, catalog, "")
  Rel(share, catalog, "")
  Rel(deliver, catalog, "", $tags="dashed")
  
  Rel(share, workflow, "")
  Rel_R(catalog, workflow, "")

  Rel(guide, cms, "")

  'LAYOUT_WITH_LEGEND()
  'HIDE_STEREOTYPE()

@enduml
