@startuml dm-c4-context 
!include <C4/C4_Context>

LAYOUT_TOP_DOWN()
'LAYOUT_AS_SKETCH()
'LAYOUT_WITH_LEGEND()
left to right direction
'title C4 System context diagram for Data Marketplace

Enterprise_Boundary(cddo, "CDDO") {
  Person(admin, "Admin", "Data marketplace administrator")
  System(dm, "Data Marketplace", "x-gov data discovery, sharing, delivery and guidance")
  admin -> dm : manages the data marketplace, including security permissions, logs, etc.
}

Enterprise_Boundary(depA, "Dept A"){
  Person(acquirerA, "Acquirer", "Needs to access data held elsewhere")
  Person(supplierA, "Supplier", "Publishes metadata about deptartmental data assets that can be shared")
  System_Ext(dmA, "Internal Data Marketplace", "Catalogue of departmental data assets")
}

Enterprise_Boundary(depB, "Dept B"){
  Person_Ext(ownerB, "Data owner", "Owns data assets that can be shared")
  Person(supplierB, "Supplier", "Publishes metadata about deptartmental data assets that can be shared")
  System_Ext(dmA, "Internal Data Marketplace", "Catalogue of departmental data assets")
  Boundary(dataassetsB, "Data assets") {
    SystemDb_Ext(dbB1,"Data\nasset 1")
    SystemDb_Ext(dbB2,"Data\nasset 2")
    Artifact "Data\nasset 3" as dbB3
    SystemDb_Ext(dbBn,"Data\nasset n")

    dbB1 -[#hidden] dbB2
    dbB1 -[#hidden]- dbB3
    dbB2 -[#hidden]- dbBn
  }
  ownerB ..> dbB2 : owns
}

Person_Ext(visitor, "Visitor", "Wants to find out about government data sharing")

supplierA --> dmA : identify/extract metadata for data assets that can be published
supplierA -up-> dm : bulk uploads metadata and publishes it in the data marketplace

supplierB --> dataassetsB : identify data assets that can be published
supplierB -up-> dm : manually enters metadata about data assets and publishes this in the data marketplace

acquirerA -up-> dm : searches for data asset and makes data sharing request once satisfied the asset meets their requirements
dm --> ownerB : receives and approves data sharing requests and begins data sharing process

dm <-up- visitor : browses public guidance materials around data marketplace and data sharing

@enduml